import { Toaster } from 'react-hot-toast'
import './admin.css'
import AdminHeader from './admin/ui/AdminHeader'
import MenuBar from './admin/ui/MenuBar'
import "@uploadthing/react/styles.css"
import { ToasterProvider } from '../context/ToasterProvider'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AdminHeader/>
        <MenuBar/>
   
        {children}
           <ToasterProvider />
        </body>
    </html>
  )
}
